.TH BASHLIGHT 1
.SH NAME
bashlight \- adjust backlight brightness using the Linux kernel sysfs interface.
.SH SYNOPSIS
.B bashlight
[\-help]
[\-version]
[\-get]
[\-list]
[\-set percent]
[\-inc percent]
[\-dec percent]
[\-save]
[\-restore]
[\-device name]
[\-kbd]
[\-perceptual]
[\-time milliseconds]
[\-steps number]
.SH DESCRIPTION
.I bashlight
is used to adjust the backlight brightness where supported. It finds all
outputs on SYSFS supporting backlight brightness control and changes
them all in the same way.
.IP \-get
Print out the current backlight brightness of each output with such a
control. The brightness is represented as a percentage of the maximum
brightness supported.
.IP "\-set \fIpercent\fP"
Sets each backlight brightness to the specified level.
.IP "\-inc \fIpercent\fP"
Increases brightness by the specified amount.
.IP "\-dec \fIpercent\fP"
Decreases brightness by the specified amount.
.IP \-list
Print out the names of the backlight devices found.
.IP \-save
Save the current brightness of each output. The state is kept under
$XDG_RUNTIME_DIR and does not survive a reboot.
.IP \-restore
Restore the brightness saved by \-save.
.IP "\-device \fIname\fP"
Apply the operation to the named device only instead of every output.
.IP \-kbd
Control keyboard backlights found under /sys/class/leds instead of
displays. Setting 0 is allowed and switches the light off.
.IP \-perceptual
Map percentages through a square curve approximating human brightness
perception, so equal steps look equally big across the range. Affects
\-get, \-set, \-inc and \-dec.
.IP \-help
Print out a summary of the usage and exit.
.IP \-version
Print out the program version and exit.
.IP "\-time \fImilliseconds\fP"
Length of time to spend fading the backlight between old and new value.
Default is 200.
.IP "\-steps \fInumber\fP"
Number of steps to take while transitioning. Default is 20
